services:

  dashboard-api:
    image: disaenz2/hello-world-api:latest
    container_name: hello-world-api
    ports:
      - 3200:3200
    #build:
      #context: ./hello-world-api
      #dockerfile: Dockerfile
  dashboard-app:
    image: hello-world-app:latest
    container_name: hello-world-app
    ports:
      - 3000:3000
    build:
      context: ./hello-world-app
      dockerfile: Dockerfile