services:

  api:
    image: disaenz2/hello-world-api:latest
    container_name: hello-world-api
    ports:
      - 3200:3200
  app:
    image: disaenz2/hello-world-app:latest
    container_name: hello-world-app
    ports:
      - 4000:3000