pipeline
{
    agent any

    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Initial Setup Process'){
            steps{
                echo 'Starting Pipeline'
                sh 'chmod +x hello-world-api/scripts/*'
            }
        }

        stage('Login to Docker Hub'){
            steps{
                sh "sh hello-world-api/scripts/docker-login.sh"
            }
        }

        stage('Build Docker Image') {
            steps{
                sh "sh hello-world-api/scripts/build-docker-image.sh"
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps{
                sh "sh hello-world-api/scripts/docker-push.sh"
            }
        }
    }  
}
