pipeline
{
    agent any

    options {
        skipStagesAfterUnstable()
    }

    stages {

        stage('Initial Notification Process'){
            steps{
                echo 'Starting Pipeline'
                sh 'cd hello-world-api'
                sh 'pwd'
                sh 'ls -la'
                sh 'chmod +x scripts/*'
            }

        }

        stage('Login to Docker Hub'){
            steps{
                sh "sh scripts/docker-login.sh"
            }
        }

        stage('Build Docker Image') {
            steps{
                sh "sh scripts/build-docker-image.sh"
            }
        }

    /*
        stage('Push Docker Image to Docker Hub') {
            steps{
                sh "sh scripts/docker-push.sh"
            }
        }
    }
    */
    }   
}
