// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("select_language", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("select_language", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect({ width: 1440, height: 816 });
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(3)"));
      await dropdown.findElement(By.xpath("//option[. = 'German']")).click();
    }
    await driver.findElement(By.css(".btn:nth-child(4)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(4)"));
      await dropdown.findElement(By.xpath("//option[. = 'Red']")).click();
    }
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(3)"));
      await dropdown.findElement(By.xpath("//option[. = 'French']")).click();
    }
    await driver.findElement(By.css(".btn:nth-child(4)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(4)"));
      await dropdown.findElement(By.xpath("//option[. = 'Green']")).click();
    }
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(3)"));
      await dropdown.findElement(By.xpath("//option[. = 'Spanish']")).click();
    }
    await driver.findElement(By.css("html")).click();
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(3)"));
      await dropdown.findElement(By.xpath("//option[. = 'Latin']")).click();
    }
    await driver.findElement(By.css(".btn:nth-child(3)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(3)"));
      await dropdown.findElement(By.xpath("//option[. = 'Mandatrin']")).click();
    }
    await driver.findElement(By.css("html")).click();
    await driver.findElement(By.css(".btn:nth-child(4)")).click();
    {
      const dropdown = await driver.findElement(By.css(".btn:nth-child(4)"));
      await dropdown.findElement(By.xpath("//option[. = 'Chocolate']")).click();
    }
  });
});
